# Generated by Django 3.0.4 on 2020-03-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('taste', models.CharField(blank=True, choices=[('SW', 'Sweet'), ('SP', 'Spicy'), ('SO', 'Sour'), ('BT', 'Bitter')], max_length=2)),
                ('cuisine', models.CharField(blank=True, choices=[('IND', 'Indian'), ('ASI', 'Asian'), ('ITA', 'Italian'), ('MEX', 'Mexican'), ('SPA', 'Spanish'), ('JAP', 'Japenese'), ('THA', 'Thai'), ('CHI', 'Chinese'), ('FRE', 'French')], max_length=3)),
                ('ingredients', models.TextField()),
                ('frecipe', models.TextField()),
                ('price', models.FloatField(default=500.0)),
            ],
        ),
    ]
