# Generated by Django 3.0.4 on 2020-03-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_dish_isveg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='taste',
            field=models.CharField(blank=True, choices=[('Sweet', 'Sweet'), ('Spicy', 'Spicy'), ('Sour', 'Sour'), ('Bitter', 'Bitter')], max_length=10),
        ),
    ]
