# Generated by Django 3.0.4 on 2020-03-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20200318_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='taste',
            field=models.CharField(blank=True, choices=[('SW', 'Sweet'), ('SP', 'Spicy'), ('SO', 'Sour'), ('BT', 'Bitter')], max_length=2),
        ),
    ]
