# Generated by Django 3.0.4 on 2020-03-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20200318_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='taste',
            field=models.CharField(blank=True, choices=[('SWEET', 'Sweet'), ('SPICY', 'Spicy'), ('SOUR', 'Sour'), ('BITTER', 'Bitter')], max_length=10),
        ),
    ]
