# Generated by Django 3.0.4 on 2020-03-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20200318_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('INDIAN', 'Indian'), ('ASIAN', 'Asian'), ('ITALIAN', 'Italian'), ('MEXICAN', 'Mexican'), ('SPANISH', 'Spanish'), ('JAPANESE', 'Japenese'), ('THAI', 'Thai'), ('CHINESE', 'Chinese'), ('FRENCH', 'French')], max_length=10),
        ),
    ]
