# Generated by Django 3.0.4 on 2020-03-18 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20200318_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('dish_name', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='recipe.Dish')),
            ],
        ),
    ]
