# Generated by Django 3.0.4 on 2020-03-18 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recipe.Order'),
        ),
    ]
